
environment:
  matrix:
    - PYTHON: "C:/Python36"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "%PYTHON%/Scripts/pip.exe install -e ."

build: off

test_script:
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/python.exe setup.py test"
